In [38]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [39]:
data = pd.read_csv('Churn_Modelling.csv')
# mapping = {'Female':0 ,'Male':1}
# data['Gender'] = data['Gender'].map(mapping)
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [40]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [41]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[: ,2] = le.fit_transform(x[: ,2])

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder' ,OneHotEncoder() ,[1])] ,remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [44]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) 
X_test = scaler.fit_transform(X_test) 

In [47]:
ann = tf.keras.models.Sequential()

In [48]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

In [49]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

In [50]:
ann.add(tf.keras.layers.Dense(units=1 ,activation='sigmoid'))

In [51]:
ann.compile(optimizer='adam' ,loss='binary_crossentropy' ,metrics=['accuracy'])

In [52]:
ann.fit(X_train ,y_train ,batch_size = 32 ,epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7452 - loss: 0.5616
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8019 - loss: 0.4583
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8095 - loss: 0.4344
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8155 - loss: 0.4214
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8271 - loss: 0.4080
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8219 - loss: 0.4103
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8203 - loss: 0.4118
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8180 - loss: 0.4021
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8284 - loss: 0.3980
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8316 - loss: 0.3880
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8292 - loss: 0.3976
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [60]:
print(ann.predict(scaler.transform([[1, 0, 1 ,600 ,1 ,40 ,3 ,60000 ,2 ,1 ,1 ,50000]]))> 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[False]]


In [62]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1531   64]
 [ 213  192]]


0.8615